# Generated by Django 3.2.2 on 2021-05-19 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_refer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Refer',
        ),
    ]
