# Generated by Django 3.2.3 on 2021-05-24 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_auto_20210524_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='alternate_contact',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='alternate_email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='district',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='imo_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_employer',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='qualification_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skype_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='territory',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='vacancies',
        ),
    ]
